/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthForm: typeof import('./components/auth/AuthForm.vue')['default']
    Button: typeof import('./components/shared/button/Button.vue')['default']
    DashboardAvatar: typeof import('./components/dashboard/DashboardAvatar.vue')['default']
    DashboardHeader: typeof import('./components/dashboard/DashboardHeader.vue')['default']
    DashboardNotification: typeof import('./components/dashboard/DashboardNotification.vue')['default']
    DashboardSearch: typeof import('./components/dashboard/DashboardSearch.vue')['default']
    DashboardSidebar: typeof import('./components/dashboard/DashboardSidebar.vue')['default']
    Editor: typeof import('./components/shared/Editor.vue')['default']
    EditorQuill: typeof import('./components/shared/EditorQuill.vue')['default']
    HotelModal: typeof import('./components/shared/modal/HotelModal.vue')['default']
    IconColorBed: typeof import('~icons/color/bed')['default']
    IconColorHotel: typeof import('~icons/color/hotel')['default']
    IconColorRoom: typeof import('~icons/color/room')['default']
    IconColorVoucher: typeof import('~icons/color/voucher')['default']
    IconCustomApp: typeof import('~icons/custom/app')['default']
    IconCustomBath: typeof import('~icons/custom/bath')['default']
    IconCustomBed: typeof import('~icons/custom/bed')['default']
    IconCustomCheckin: typeof import('~icons/custom/checkin')['default']
    IconCustomError: typeof import('~icons/custom/error')['default']
    IconCustomHotel: typeof import('~icons/custom/hotel')['default']
    IconCustomLeftArrow: typeof import('~icons/custom/left-arrow')['default']
    IconCustomMoney: typeof import('~icons/custom/money')['default']
    IconCustomRate: typeof import('~icons/custom/rate')['default']
    IconCustomSiphoriaNotext: typeof import('~icons/custom/siphoria-notext')['default']
    IconCustomVoucher: typeof import('~icons/custom/voucher')['default']
    'IconIc:baselineMoreVert': typeof import('~icons/ic/baseline-more-vert')['default']
    'IconIc:outlineMoreVert': typeof import('~icons/ic/outline-more-vert')['default']
    'IconIc:roundPlus': typeof import('~icons/ic/round-plus')['default']
    'IconMaterialSymbols:lockOpenOutline': typeof import('~icons/material-symbols/lock-open-outline')['default']
    'IconMaterialSymbols:lockOutline': typeof import('~icons/material-symbols/lock-outline')['default']
    'IconMdi:trashCanOutline': typeof import('~icons/mdi/trash-can-outline')['default']
    'IconPh:bellBold': typeof import('~icons/ph/bell-bold')['default']
    'IconPh:xBold': typeof import('~icons/ph/x-bold')['default']
    LoginForm: typeof import('./components/auth/LoginForm.vue')['default']
    Modal: typeof import('./components/shared/modal/Modal.vue')['default']
    NPopover: typeof import('naive-ui')['NPopover']
    Popover: typeof import('./components/shared/popover/Popover.vue')['default']
    Popselect: typeof import('./components/shared/popselect/Popselect.vue')['default']
    RoomCardAction: typeof import('./components/hotel/RoomCardAction.vue')['default']
    RoomCardActionItem: typeof import('./components/hotel/RoomCardActionItem.vue')['default']
    RoomCardItem: typeof import('./components/hotel/RoomCardItem.vue')['default']
    RoomScreen: typeof import('./components/hotel/RoomScreen.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingCardItem: typeof import('./components/hotel/SettingCardItem.vue')['default']
    SettingScreen: typeof import('./components/hotel/SettingScreen.vue')['default']
    SidebarHotel: typeof import('./components/dashboard/SidebarHotel.vue')['default']
    SidebarItem: typeof import('./components/dashboard/SidebarItem.vue')['default']
    SignupForm: typeof import('./components/auth/SignupForm.vue')['default']
  }
}
